# Generated by Django 4.2.24 on 2025-11-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('is_trasversale', models.BooleanField(default=False)),
                ('local_project_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('oc_project_status', models.CharField(choices=[('Concluso', 'Concluso'), ('Liquidato', 'Liquidato'), ('In corso', 'In corso'), ('Non avviato', 'Non avviato'), ('Non applicabile', 'Non applicabile')], default='Non applicabile', max_length=100)),
                ('oc_procedural_state', models.CharField(choices=[('Non avviato', 'Non avviato'), ('In avvio di progettazione', 'In avvio di progettazione'), ('In corso di progettazione', 'In corso di progettazione'), ('In affidamento', 'In affidamento'), ('In esecuzione', 'In esecuzione'), ('Eseguito', 'Eseguito')], default='Non avviato', max_length=100)),
                ('cup_typology', models.CharField(blank=True, choices=[('ACQUISTO DI IMMOBILIZZAZIONI', 'Acquisto di immobilizzazioni'), ('ACQUISTO SERVIZI REALI (INCLUDE FORMAZIONE)', 'Acquisto servizi reali (include formazione)'), ('ACQUISTO SERVIZI REALI (INCLUSA FORMAZIONE)', 'Acquisto servizi reali (inclusa formazione)'), ('ALTRO', 'Altro'), ('AMMODERNAMENTO', 'Ammodernamento'), ('AMMODERNAMENTO TECNOLOGICO E LABORATORIALE', 'Ammodernamento tecnologico e laboratoriale'), ('AMPLIAMENTO', 'Ampliamento'), ('APPLICATIVI E PIATTAFORME WEB', 'Applicativi e piattaforme web'), ('ASSISTENZA', 'Assistenza'), ("ATTIVITA' DI RICERCA", 'Attività di ricerca'), ('CONSULENZE', 'Consulenze'), ('CORSI DI FORMAZIONE', 'Corsi di formazione'), ('COSTITUZIONE O INCREMENTO DI FONDO PER PRESTITO', 'Costituzione o incremento di fondo per prestito'), ('INCENTIVI AL LAVORO', 'Incentivi al lavoro'), ('LAVORI SOCIALMENTE UTILI', 'Lavori socialmente utili'), ('MANUTENZIONE ORDINARIA', 'Manutenzione ordinaria'), ('MANUTENZIONE STRAORDINARIA', 'Manutenzione straordinaria'), ('MANUTENZIONE STRAORDINARIA CON EFFICIENTAMENTO ENERGETICO', 'Manutenzione straordinaria con efficientamento energetico'), ('MANUTENZIONE STRAORDINARIA DI ADEGUAMENTO IMPIANTISTICA E O ANTINCENDIO', 'Manutenzione straordinaria adeguamento impiantistica e/o antincendio'), ('MANUTENZIONE STRAORDINARIA DI ADEGUAMENTO SISMICO', 'Manutenzione straordinaria adeguamento sismico'), ('MANUTENZIONE STRAORDINARIA DI MIGLIORAMENTO SISMICO', 'Manutenzione straordinaria miglioramento sismico'), ("MANUTENZIONE STRAORDINARIA PER ACCESSIBILITA' E ABBATTIMENTO DELLE BARRIERE ARCHITETTONICHE", 'Manutenzione straordinaria per accessibilità e abbattimento delle barriere architettoniche'), ('MANUTENZIONE STRAORDINARIA PER MESSA IN SICUREZZA (ESCLUSO DISSESTO IDROGEOLOGICO)', 'Manutenzione straordinaria per messa in sicurezza (escluso dissesto idrogeologico)'), ('NUOVA FORNITURA', 'Nuova fornitura'), ('NUOVA REALIZZAZIONE', 'Nuova realizzazione'), ('NUOVA REALIZZAZIONE CON EFFICIENTAMENTO ENERGETICO', 'Nuova realizzazione con efficientamento energetico'), ('PROGETTI DI RICERCA', 'Progetti di ricerca'), ('RECUPERO', 'Recupero'), ('RESTAURO', 'Restauro'), ('RICONVERSIONE', 'Riconversione'), ("RISTRUTTURAZIONE (PER CAMBIO DI DESTINAZIONE D'USO)", "Ristrutturazione (per cambio di destinazione d'uso)"), ('RISTRUTTURAZIONE CON EFFICIENTAMENTO ENERGETICO', 'Ristrutturazione con efficientamento energetico'), ('SOSTEGNO AL REDDITO CON RISORSE FSC E/O SIE', 'Sostegno al reddito con risorse FSC e/o SIE'), ('STUDI E PROGETTAZIONI', 'Studi e progettazioni'), ('STUDI E PROGETTAZIONI O PIANIFICAZIONE TERRITORIALE', 'Studi e progettazioni o pianificazione territoriale'), ('STUDI E PROGETTAZIONI PER EFFICIENTAMENTO ENERGETICO', 'Studi e progettazioni per efficientamento energetico'), ('TRASFERIMENTO', 'Trasferimento'), ('DEMOLIZIONE', 'Demolizione'), ('ACQUISTO DI IMMOBILIZZAZIONI (AD ESEMPIO PESCHERECCI O AZIENDE)', 'Acquisto di immobilizzazioni (ad esempio pescherecci o aziende)'), ('AMMODERNAMENTO CON EFFICIENTAMENTO ENERGETICO', 'Ammodernamento con efficientamento energetico'), ('AMPLIAMENTO (COMPRESA SOPRAELEVAZIONE) O POTENZIAMENTO', 'Ampliamento (compresa sopraelevazione) o potenziamento'), ('AMPLIAMENTO CON EFFICIENTAMENTO ENERGETICO', 'Ampliamento con efficientamento energetico'), ('BREVETTI', 'Brevetti'), ('COSTITUZIONE O INCREMENTO DI FONDO PER GARANZIA', 'Costituzione o incremento di fondo per garanzia'), ('MANUTENZIONE CON EFFICIENTAMENTO ENERGETICO', 'Manutenzione con efficientamento energetico'), ('MANUTENZIONE STRAORDINARIA PER DISSESTO IDROGEOLOGICO', 'Manutenzione straordinaria per dissesto idrogeologico'), ('RISTRUTTURAZIONE', 'Ristrutturazione'), ('STUDI E PROGETTAZIONI PER ABBATTIMENTO BARRIERE ARCHITETTONICHE', 'Studi e progettazioni per abbattimento barriere architettoniche'), ('STUDI E PROGETTAZIONI PER AMMODERNAMENTO TECNOLOGICO E LABORATORIALE', 'Studi e progettazioni per ammodernamento tecnologico e laboratoriale'), ('STUDI E PROGETTAZIONI PER DISSESTO IDROGEOLOGICO', 'Studi e progettazioni per dissesto idrogeologico'), ('STUDI E PROGETTAZIONI PER IL MIGLIORAMENTO SISMICO', 'Studi e progettazioni per il miglioramento sismico'), ("STUDI E PROGETTAZIONI PER L'ADEGUAMENTO SISMICO", "Studi e progettazioni per l'adeguamento sismico"), ('STUDI E PROGETTAZIONI PER MESSA IN SICUREZZA (ESCLUSO DISSESTO IDROGEOLOGICO)', 'Studi e progettazioni per messa in sicurezza (escluso dissesto idrogeologico)'), ('STUDI E PROGETTAZIONI PER NUOVA REALIZZAZIONE', 'Studi e progettazioni per nuova realizzazione'), ('STUDI E PROGETTAZIONI PER RECUPERO', 'Studi e progettazioni per recupero')], max_length=255, null=True)),
                ('oc_project_title', models.TextField()),
                ('cup_descr_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('oc_synthetic_theme', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('region_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=50)),
                ('macroarea', models.CharField(choices=[('Altro', 'Altro'), ('Ambito Nazionale', 'Ambito Nazionale'), ('Centro-Nord', 'Centro-Nord'), ('Estero', 'Estero'), ('Mezzogiorno', 'Mezzogiorno')], default='Altro', max_length=50, verbose_name='Macro Area')),
                ('project', models.ManyToManyField(related_name='locations', to='analytics_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eu_funds', models.FloatField(default=0)),
                ('eu_funds_fesr', models.FloatField(default=0)),
                ('eu_funds_fse', models.FloatField(default=0)),
                ('eu_funds_feasr', models.FloatField(default=0)),
                ('eu_funds_feamp', models.FloatField(default=0)),
                ('eu_funds_iog', models.FloatField(default=0)),
                ('state_rotating_fund', models.FloatField(default=0)),
                ('state_fsc', models.FloatField(default=0)),
                ('state_pac', models.FloatField(default=0)),
                ('state_completions', models.FloatField(default=0)),
                ('state_other_measures', models.FloatField(default=0)),
                ('regional_funds', models.FloatField(default=0)),
                ('provincial_funds', models.FloatField(default=0)),
                ('municipal_funds', models.FloatField(default=0)),
                ('freed_resources', models.FloatField(default=0)),
                ('other_public_funds', models.FloatField(default=0)),
                ('foreign_state', models.FloatField(default=0)),
                ('private_funds', models.FloatField(default=0)),
                ('funds_to_find', models.FloatField(default=0)),
                ('total_savings', models.FloatField(default=0)),
                ('total_public_savings', models.FloatField(default=0)),
                ('total_funds_gross', models.FloatField(blank=True, null=True)),
                ('total_funds_net', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding', to='analytics_projects.project')),
            ],
        ),
    ]
