# Generated by Django 5.2.8 on 2025-11-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('local_project_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('oc_project_status', models.CharField(choices=[('Concluso', 'Concluso'), ('Liquidato', 'Liquidato'), ('In corso', 'In corso'), ('Non avviato', 'Non avviato'), ('Non applicabile', 'Non applicabile')], default='Non applicabile', max_length=30)),
                ('oc_procedural_state', models.CharField(choices=[('Non avviato', 'Non avviato'), ('In avvio di progettazione', 'In avvio di progettazione'), ('In corso di progettazione', 'In corso di progettazione'), ('In affidamento', 'In affidamento'), ('In esecuzione', 'In esecuzione'), ('Eseguito', 'Eseguito')], default='Non avviato', max_length=30)),
                ('oc_project_title', models.CharField(max_length=255)),
                ('cup_descr_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('oc_synthetic_theme', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('region_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=20)),
                ('macroarea', models.CharField(choices=[('ALTRO', 'ALTRO'), ('AMBITO NAZIONALE', 'AMBITO NAZIONALE'), ('CENTRO-NORD', 'CENTRO-NORD'), ('ESTERO', 'ESTERO'), ('MEZZOGIORNO', 'MEZZOGIORNO'), ('TRASVERSALE', 'TRASVERSALE')], default='ALTRO', max_length=20, verbose_name='Macro Area')),
                ('project', models.ManyToManyField(related_name='locations', to='analytics_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eu_funds', models.FloatField(default=0)),
                ('eu_funds_fesr', models.FloatField(default=0)),
                ('eu_funds_fse', models.FloatField(default=0)),
                ('eu_funds_feasr', models.FloatField(default=0)),
                ('eu_funds_feamp', models.FloatField(default=0)),
                ('eu_funds_iog', models.FloatField(default=0)),
                ('state_rotating_fund', models.FloatField(default=0)),
                ('state_fsc', models.FloatField(default=0)),
                ('state_pac', models.FloatField(default=0)),
                ('state_completions', models.FloatField(default=0)),
                ('state_other_measures', models.FloatField(default=0)),
                ('regional_funds', models.FloatField(default=0)),
                ('provincial_funds', models.FloatField(default=0)),
                ('municipal_funds', models.FloatField(default=0)),
                ('freed_resources', models.FloatField(default=0)),
                ('other_public_funds', models.FloatField(default=0)),
                ('foreign_state', models.FloatField(default=0)),
                ('private_funds', models.FloatField(default=0)),
                ('funds_to_find', models.FloatField(default=0)),
                ('total_savings', models.FloatField(default=0)),
                ('total_public_savings', models.FloatField(default=0)),
                ('total_funds_gross', models.FloatField(blank=True, null=True)),
                ('total_funds_net', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_projects.project')),
            ],
        ),
    ]
