# Generated by Django 4.2.26 on 2025-11-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='local_project_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='oc_procedural_state',
            field=models.CharField(choices=[('Non avviato', 'Non avviato'), ('In avvio di progettazione', 'In avvio di progettazione'), ('In corso di progettazione', 'In corso di progettazione'), ('In affidamento', 'In affidamento'), ('In esecuzione', 'In esecuzione'), ('Eseguito', 'Eseguito')], default='Non avviato', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='oc_project_status',
            field=models.CharField(choices=[('Concluso', 'Concluso'), ('Liquidato', 'Liquidato'), ('In corso', 'In corso'), ('Non avviato', 'Non avviato'), ('Non applicabile', 'Non applicabile')], default='Non applicabile', max_length=100),
        ),
    ]
