# Generated by Django 4.2.26 on 2025-11-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_projects', '0002_alter_project_local_project_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='oc_project_title',
            field=models.TextField(),
        ),
    ]
