# Generated by Django 4.2.26 on 2025-11-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_projects', '0003_alter_project_oc_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='macroarea',
            field=models.CharField(choices=[('ALTRO', 'ALTRO'), ('AMBITO NAZIONALE', 'AMBITO NAZIONALE'), ('CENTRO-NORD', 'CENTRO-NORD'), ('ESTERO', 'ESTERO'), ('MEZZOGIORNO', 'MEZZOGIORNO'), ('TRASVERSALE', 'TRASVERSALE')], default='ALTRO', max_length=50, verbose_name='Macro Area'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='region_name',
            field=models.CharField(max_length=50),
        ),
    ]
