# Generated by Django 4.2.26 on 2025-11-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_projects', '0004_alter_location_macroarea_alter_location_region_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding', to='analytics_projects.project'),
        ),
    ]
