# Generated by Django 4.2.24 on 2025-11-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_projects', '0005_alter_funding_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cup_typology',
            field=models.CharField(blank=True, choices=[('ACQUISTO DI IMMOBILIZZAZIONI', 'Purchase Fixed Assets'), ('ACQUISTO SERVIZI REALI (INCLUDE FORMAZIONE)', 'Purchase Real Services'), ('ACQUISTO SERVIZI REALI (INCLUSA FORMAZIONE)', 'Purchase Real Services2'), ('ALTRO', 'Other'), ('AMMODERNAMENTO', 'Modernization'), ('AMMODERNAMENTO TECNOLOGICO E LABORATORIALE', 'Technological Laboratory Modernization'), ('AMPLIAMENTO', 'Expansion'), ('APPLICATIVI E PIATTAFORME WEB', 'Web Apps Platforms'), ('ASSISTENZA', 'Assistance'), ("ATTIVITA' DI RICERCA", 'Research Activity'), ('CONSULENZE', 'Consultancy'), ('CORSI DI FORMAZIONE', 'Training Courses'), ('COSTITUZIONE O INCREMENTO DI FONDO PER PRESTITO', 'Fund Establishment'), ('INCENTIVI AL LAVORO', 'Work Incentives'), ('LAVORI SOCIALMENTE UTILI', 'Social Works'), ('MANUTENZIONE ORDINARIA', 'Ordinary Maintenance'), ('MANUTENZIONE STRAORDINARIA', 'Extraordinary Maintenance'), ('MANUTENZIONE STRAORDINARIA CON EFFICIENTAMENTO ENERGETICO', 'Extraordinary Maintenance Energy'), ('MANUTENZIONE STRAORDINARIA DI ADEGUAMENTO IMPIANTISTICA E O ANTINCENDIO', 'Extraordinary Maintenance Antifire'), ('MANUTENZIONE STRAORDINARIA DI ADEGUAMENTO SISMICO', 'Extraordinary Maintenance Seismic'), ('MANUTENZIONE STRAORDINARIA DI MIGLIORAMENTO SISMICO', 'Extraordinary Maintenance Seismic Improv'), ("MANUTENZIONE STRAORDINARIA PER ACCESSIBILITA' E ABBATTIMENTO DELLE BARRIERE ARCHITETTONICHE", 'Extraordinary Maintenance Accessibility'), ('MANUTENZIONE STRAORDINARIA PER MESSA IN SICUREZZA (ESCLUSO DISSESTO IDROGEOLOGICO)', 'Extraordinary Maintenance Safety'), ('NUOVA FORNITURA', 'New Supply'), ('NUOVA REALIZZAZIONE', 'New Realization'), ('NUOVA REALIZZAZIONE CON EFFICIENTAMENTO ENERGETICO', 'New Realization Energy'), ('PROGETTI DI RICERCA', 'Research Projects'), ('RECUPERO', 'Recovery'), ('RESTAURO', 'Restoration'), ('RICONVERSIONE', 'Reconversion'), ("RISTRUTTURAZIONE (PER CAMBIO DI DESTINAZIONE D'USO)", 'Restructuring'), ('RISTRUTTURAZIONE CON EFFICIENTAMENTO ENERGETICO', 'Restructuring Energy'), ('SOSTEGNO AL REDDITO CON RISORSE FSC E/O SIE', 'Income Support'), ('STUDI E PROGETTAZIONI', 'Studies Designs'), ('STUDI E PROGETTAZIONI O PIANIFICAZIONE TERRITORIALE', 'Studies Territorial Planning'), ('STUDI E PROGETTAZIONI PER EFFICIENTAMENTO ENERGETICO', 'Studies Designs Energy'), ('TRASFERIMENTO', 'Transfer')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='macroarea',
            field=models.CharField(choices=[('Altro', 'Altro'), ('Ambito Nazionale', 'Ambito Nazionale'), ('Centro-Nord', 'Centro-Nord'), ('Estero', 'Estero'), ('Mezzogiorno', 'Mezzogiorno'), ('Traversale', 'Trasversale')], default='Altro', max_length=50, verbose_name='Macro Area'),
        ),
    ]
