# Generated by Django 4.2.24 on 2025-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_projects', '0006_project_cup_typology_alter_location_macroarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='macroarea',
            field=models.CharField(choices=[('Altro', 'Altro'), ('Ambito Nazionale', 'Ambito Nazionale'), ('Centro-Nord', 'Centro-Nord'), ('Estero', 'Estero'), ('Mezzogiorno', 'Mezzogiorno'), ('Trasversale', 'Trasversale')], default='Altro', max_length=50, verbose_name='Macro Area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cup_typology',
            field=models.CharField(blank=True, choices=[('ACQUISTO DI IMMOBILIZZAZIONI', 'Acquisto di immobilizzazioni'), ('ACQUISTO SERVIZI REALI (INCLUDE FORMAZIONE)', 'Acquisto servizi reali (include formazione)'), ('ACQUISTO SERVIZI REALI (INCLUSA FORMAZIONE)', 'Acquisto servizi reali (inclusa formazione)'), ('ALTRO', 'Altro'), ('AMMODERNAMENTO', 'Ammodernamento'), ('AMMODERNAMENTO TECNOLOGICO E LABORATORIALE', 'Ammodernamento tecnologico e laboratoriale'), ('AMPLIAMENTO', 'Ampliamento'), ('APPLICATIVI E PIATTAFORME WEB', 'Applicativi e piattaforme web'), ('ASSISTENZA', 'Assistenza'), ("ATTIVITA' DI RICERCA", 'Attività di ricerca'), ('CONSULENZE', 'Consulenze'), ('CORSI DI FORMAZIONE', 'Corsi di formazione'), ('COSTITUZIONE O INCREMENTO DI FONDO PER PRESTITO', 'Costituzione o incremento di fondo per prestito'), ('INCENTIVI AL LAVORO', 'Incentivi al lavoro'), ('LAVORI SOCIALMENTE UTILI', 'Lavori socialmente utili'), ('MANUTENZIONE ORDINARIA', 'Manutenzione ordinaria'), ('MANUTENZIONE STRAORDINARIA', 'Manutenzione straordinaria'), ('MANUTENZIONE STRAORDINARIA CON EFFICIENTAMENTO ENERGETICO', 'Manutenzione straordinaria con efficientamento energetico'), ('MANUTENZIONE STRAORDINARIA DI ADEGUAMENTO IMPIANTISTICA E O ANTINCENDIO', 'Manutenzione straordinaria adeguamento impiantistica e/o antincendio'), ('MANUTENZIONE STRAORDINARIA DI ADEGUAMENTO SISMICO', 'Manutenzione straordinaria adeguamento sismico'), ('MANUTENZIONE STRAORDINARIA DI MIGLIORAMENTO SISMICO', 'Manutenzione straordinaria miglioramento sismico'), ("MANUTENZIONE STRAORDINARIA PER ACCESSIBILITA' E ABBATTIMENTO DELLE BARRIERE ARCHITETTONICHE", 'Manutenzione straordinaria per accessibilità e abbattimento delle barriere architettoniche'), ('MANUTENZIONE STRAORDINARIA PER MESSA IN SICUREZZA (ESCLUSO DISSESTO IDROGEOLOGICO)', 'Manutenzione straordinaria per messa in sicurezza (escluso dissesto idrogeologico)'), ('NUOVA FORNITURA', 'Nuova fornitura'), ('NUOVA REALIZZAZIONE', 'Nuova realizzazione'), ('NUOVA REALIZZAZIONE CON EFFICIENTAMENTO ENERGETICO', 'Nuova realizzazione con efficientamento energetico'), ('PROGETTI DI RICERCA', 'Progetti di ricerca'), ('RECUPERO', 'Recupero'), ('RESTAURO', 'Restauro'), ('RICONVERSIONE', 'Riconversione'), ("RISTRUTTURAZIONE (PER CAMBIO DI DESTINAZIONE D'USO)", "Ristrutturazione (per cambio di destinazione d'uso)"), ('RISTRUTTURAZIONE CON EFFICIENTAMENTO ENERGETICO', 'Ristrutturazione con efficientamento energetico'), ('SOSTEGNO AL REDDITO CON RISORSE FSC E/O SIE', 'Sostegno al reddito con risorse FSC e/o SIE'), ('STUDI E PROGETTAZIONI', 'Studi e progettazioni'), ('STUDI E PROGETTAZIONI O PIANIFICAZIONE TERRITORIALE', 'Studi e progettazioni o pianificazione territoriale'), ('STUDI E PROGETTAZIONI PER EFFICIENTAMENTO ENERGETICO', 'Studi e progettazioni per efficientamento energetico'), ('TRASFERIMENTO', 'Trasferimento')], max_length=255, null=True),
        ),
    ]
