# Generated by Django 4.2.24 on 2025-11-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_projects', '0007_alter_location_macroarea_alter_project_cup_typology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_trasversale',
            field=models.BooleanField(default=False),
        ),
    ]
